require: rubocop-rspec

LineLength:
  Max: 120

Metrics/ModuleLength:
  Max: 150

Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb

RSpec/ExampleLength:
  Max: 20

RSpec/MultipleExpectations:
  Max: 5

# FIXME: These need renabling once tests can be cleaned-up.
RSpec/VerifiedDoubles:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

RSpec/SubjectStub:
  Enabled: false
