require: rubocop-rspec

LineLength:
  Max: 120

Metrics/ModuleLength:
  Max: 150
  
# This is a stupid lint. Yes, module_function is more explanatory than extend self for most use cases. However, the
# former does not work if you want the methods to be able to call private methods; the latter does. See
# https://practicingruby.com/articles/ruby-and-the-singleton-pattern-dont-get-along for a detailed explanation of the
# problem.
ModuleFunction:
  Enabled: False

# FIXME: Only enabling because we are using the singleton pattern still for the
# Env and TaskEnv classes and they store memoized values that need to be
# preserved even after mixing in. Without class vars, this does not work. We
# plan to refactor these singletons out and into class instances that are passed
# around instead as needed.
ClassVars:
  Enabled: False
